server:
  port: ${APP_PORT:8080}
spring:
  jpa.hibernate:
    ddl-auto: update
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
logging:
  file:
    name: application.log
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true